version: '3.8'

services:
  auth_ms:
    container_name: auth_ms
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "wget -qO- http://localhost:4500/ping | grep -q '\"message\": *\"pong\"'" ]
      interval: 300s
      timeout: 10s
      retries: 3
    env_file:
      - ./.env
      - ./db.env
    ports:
      - "4500:4500"
    volumes:
      - .:/app

  pgsql:
    container_name: postgresql
    image: postgres:latest
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d blueprint -U postgres" ]
      interval: 30s
      timeout: 5s
      retries: 10
    env_file:
      - ./db.env
    ports:
      - "5433:5432"
    volumes:
      - psql_volume:/var/lib/postgresql/data

volumes:
  psql_volume:
