version: '3.8'

services:
  auth_ms:
    container_name: auth_ms
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env
      - ./db.env
    ports:
      - "4545:4545"
    volumes:
      - .:/app

  pgsql:
    container_name: postgresql
    image: postgres:latest
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d blueprint -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 10
    env_file:
      - ./db.env
    ports:
      - "5433:5432"
    volumes:
      - psql_volume:/var/lib/postgresql/data

volumes:
  psql_volume: